name: mytime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_storage:
  get:
  intl:
  google_fonts:
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  meta: ^1.11.0
  bloc: ^8.1.4
  date_picker_timeline: ^1.2.6
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#42a5f5"

  android_12:
    image: assets/images/splash_screen.png
    color: "#42a5f5"

